### PR TITLE
Submit on ctrl+enter

### PR DESCRIPTION
**Pull request by Errorname**
Implements #35

### CODE REVIEW

**Comment by hgwood** [comment]
This looks like pressing Ctrl+Enter while reading a question (not edition) will toggle edition mode. Am I correct?

**Comment by Errorname** [comment]
No, theses lines are in Edit and Answer which are the components shown when editing

**Comment by hgwood** [comment]
OK. I have 2 comments:
- Is it intentional to have the listener attached on `document` instead of the text area? This means the user can press ctrl+enter anywhere and it will submit the question/answer. That might be OK, I don't know.
- It might be interesting to have this behavior in a separate component or HOC. I'm not asking you to do it. Just suggesting :).

**Comment by Errorname** [comment]
Those are valid comments 👍 I will implements the changes

**Pull request merged**
